<?php

declare(strict_types=1);

namespace App\Tests;

use Brainshaker95\PhpToTsBundle\Model\TsEnum;
use Brainshaker95\PhpToTsBundle\Model\TsProperty;
use Brainshaker95\PhpToTsBundle\Tool\Converter;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\Small;
use PHPUnit\Framework\TestCase;

/**
 * @internal
 *
 * @PhpCsFixerIgnore heredoc_indentation
 */
#[Small]
#[CoversClass(TsEnum::class)]
final class TsEnumTest extends TestCase
{
    public function testToString(): void
    {
        $tsEnum = new TsEnum('enumName', Converter::TYPE_INT, properties: [
            new TsProperty('propertyName', TsProperty::TYPE_UNKNOWN),
        ]);

        self::assertSame($tsEnum->toString(), $tsEnum->__toString());

        self::assertStringEqualsStringIgnoringLineEndings(<<<'EOT'
/**
 * Auto-generated by PhpToTsBundle
 * Do not modify directly!
 */

export const ENUM_NAME = <const>{
  propertyName: unknown;
} satisfies Record<string, number>;

export type enumName = typeof ENUM_NAME[keyof typeof ENUM_NAME];
EOT, '' . $tsEnum);
    }
}
