<?php

declare(strict_types=1);

namespace App\Tests;

use Brainshaker95\PhpToTsBundle\Model\TsInterface;
use Brainshaker95\PhpToTsBundle\Model\TsProperty;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\Small;
use PHPUnit\Framework\TestCase;

/**
 * @internal
 *
 * @PhpCsFixerIgnore heredoc_indentation
 */
#[Small]
#[CoversClass(TsInterface::class)]
final class TsInterfaceTest extends TestCase
{
    public function testToString(): void
    {
        $tsInterface = new TsInterface('InterfaceName', properties: [
            new TsProperty('propertyName', TsProperty::TYPE_UNKNOWN),
        ]);

        self::assertSame($tsInterface->toString(), $tsInterface->__toString());

        self::assertStringEqualsStringIgnoringLineEndings(<<<'EOT'
/**
 * Auto-generated by PhpToTsBundle
 * Do not modify directly!
 */

export interface InterfaceName {
  propertyName: unknown;
}
EOT, '' . $tsInterface);
    }
}
