/**
 * Auto-generated by PhpToTsBundle
 * Do not modify directly!
 */

/**
 * @internal
 */
export const INT_ENUM = <const>{
  CASE_1: 0,
  CASE_2: 1,
  CASE_3: 2,
  CASE_4: 4,
  CASE_5: 8,
} satisfies Record<string, number>;

/**
 * @internal
 */
export type IntEnum = typeof INT_ENUM[keyof typeof INT_ENUM];
