/**
 * Auto-generated by PhpToTsBundle
 * Do not modify directly!
 */

/**
 * @internal
 */
declare var INT_ENUM: {
			CASE_1: 0,
			CASE_2: 1,
			CASE_3: 2,
			CASE_4: 4,
			CASE_5: 8,
};

/**
 * @internal
 */
declare type IntEnum = typeof INT_ENUM[keyof typeof INT_ENUM];
