/**
 * Auto-generated by PhpToTsBundle
 * Do not modify directly!
 */

/**
 * This is a class description
 */
export interface IterableTypes {
  testProperty1: string[];
  testProperty10: {
    [key: string]: unknown;
    '0': (1.0 | string);
    foo: string;
  };
  testProperty2: string[][];
  testProperty3: Array<number>;
  testProperty4: Record<string, boolean>;
  testProperty5: Record<string, Array<number>>;
  testProperty6: Record<string, Record<number, string[]>>;
  testProperty7: {
    foo: string;
    bar: {
      foo: {
        foo: number;
      };
    };
    baz: ({
      foo: (boolean | 'foo');
    } | null);
  };
  testProperty8: unknown[];
  testProperty9: [
    string,
    ...unknown[],
  ];
}
