/**
 * Auto-generated by PhpToTsBundle
 * Do not modify directly!
 */

/**
 * This is a class description.
 */
declare type IterableTypes = {
			testProperty7: {
						foo: string;
						bar: {
									foo: {
												foo: number;
									};
						};
						baz: ({
									foo: (boolean | "foo");
						} | null);
			};
			testProperty6: Record<string, Record<number, string[]>>;
			testProperty5: Record<string, Array<number>>;
			testProperty4: Record<string, boolean>;
			testProperty3: Array<number>;
			testProperty2: string[][];
			testProperty1: string[];
}
