/**
 * Auto-generated by PhpToTsBundle
 * Do not modify directly!
 */

declare type NativeTypes = {
			testProperty9: unknown[];
			testProperty8: boolean;
			testProperty7: string;
			testProperty6: number;
			testProperty5: number;
			/**
			 * @deprecated
			 */
			testProperty4: unknown;
			/**
			 * @deprecated
			 */
			testProperty3: string;
			/**
			 * @deprecated
			 */
			readonly testProperty2: string;
			testProperty15: unknown;
			/**
			 * This is the description for testProperty14
			 * with a newline
			 * and another one.
			 */
			testProperty14: (number | null);
			/**
			 * This is the description for testProperty13.
			 *
			 * @deprecated it is also deprecated
			 */
			testProperty13: (number | null);
			/**
			 * This is the description for testProperty12.
			 *
			 * @deprecated
			 */
			testProperty12: unknown;
			/**
			 * @deprecated
			 */
			testProperty11: unknown;
			testProperty10: unknown[];
			/**
			 * This is the description for testProperty1
			 *
			 * @deprecated
			 */
			testProperty1: string;
}
