/**
 * Auto-generated by PhpToTsBundle
 * Do not modify directly!
 */

import type { Bar } from './Bar';
import type { Foo } from './Foo';

export interface NativeTypes {
   /**
    * @deprecated
    */
   readonly testProperty2: string;
   /**
    * This is the description for testProperty1
    *
    * @deprecated
    */
   testProperty1: string;
   /**
    * @deprecated
    */
   testProperty3: string;
   /**
    * @deprecated
    */
   testProperty4: unknown;
   testProperty10: unknown[];
   /**
    * @deprecated
    */
   testProperty11: unknown;
   /**
    * This is the description for testProperty12.
    *
    * @deprecated
    */
   testProperty12: unknown;
   /**
    * This is the description for testProperty13.
    *
    * @deprecated it is also deprecated
    */
   testProperty13: (number | null);
   /**
    * This is the description for testProperty14
    * with a newline
    * and another one.
    */
   testProperty14: (number | null);
   testProperty15: unknown;
   testProperty16: unknown;
   testProperty17: unknown;
   testProperty18: (Foo & Bar);
   testProperty19: (string | false);
   testProperty20: true;
   testProperty5: number;
   testProperty6: number;
   testProperty7: string;
   testProperty8: boolean;
   testProperty9: unknown[];
}
