/**
 * Auto-generated by PhpToTsBundle
 * Do not modify directly!
 */

import type { IntEnum } from './IntEnum';
import type { StringEnum } from './StringEnum';
import type { ValueOf } from './ValueOf';

/**
 * @internal
 */
export interface SpecialTypes {
   testProperty1: ValueOf<[
      'foo',
      'bar',
      'baz',
   ]>;
   testProperty2: keyof {
      foo1: 'foo2';
      bar1: 'bar2';
      baz1: 'baz2';
   };
   testProperty3: ('foo' | 'bar');
   testProperty4: StringEnum;
   testProperty5: IntEnum;
}
