/**
 * Auto-generated by PhpToTsBundle
 * Do not modify directly!
 */

import type { IntEnum } from './int-enum';
import type { StringEnum } from './string-enum';
import type { ValueOf } from './value-of';

/**
 * @internal
 */
export interface SpecialTypes {
  testProperty1: ValueOf<[
    'foo',
    'bar',
    'baz',
  ]>;
  testProperty2: keyof {
    foo1: 'foo2';
    bar1: 'bar2';
    baz1: 'baz2';
  };
  testProperty3: ('foo' | 'bar');
  testProperty4: StringEnum;
  testProperty5: IntEnum;
}
