/**
 * Auto-generated by PhpToTsBundle
 * Do not modify directly!
 */

/**
 * @internal
 */
declare type SpecialTypes = {
			testProperty7: {
						foo1: "foo2";
						bar1: "bar2";
						baz1: "baz2";
			}["foo1"];
			testProperty6: {
						foo: "bar";
			}["foo"];
			testProperty5: IntEnum;
			testProperty4: StringEnum;
			testProperty3: ("foo" | "bar");
			testProperty2: keyof {
						foo1: "foo2";
						bar1: "bar2";
						baz1: "baz2";
			};
			testProperty1: ValueOf<[
						"foo",
						"bar",
						"baz",
			]>;
}
