/**
 * Auto-generated by PhpToTsBundle
 * Do not modify directly!
 */

/**
 * @internal
 */
declare var STRING_ENUM: {
			CASE_1: "Case 1",
			CASE_2: "Case 2",
			CASE_3: "Case 3",
			CASE_4: "Case 4",
			CASE_5: "Case 5",
};

/**
 * @internal
 */
declare type StringEnum = typeof STRING_ENUM[keyof typeof STRING_ENUM];
