/**
 * Auto-generated by PhpToTsBundle
 * Do not modify directly!
 */

/**
 * @internal
 */
export const STRING_ENUM = <const>{
  CASE_1: 'Case 1',
  CASE_2: 'Case 2',
  CASE_3: 'Case 3',
  CASE_4: 'Case 4',
  CASE_5: 'Case 5',
} satisfies Record<string, string>;

/**
 * @internal
 */
export type StringEnum = typeof STRING_ENUM[keyof typeof STRING_ENUM];
